import { CreativeMemoryItem } from "../types";

export const BROADCAST_ASSET_ITEMS: CreativeMemoryItem[] = [
  // 1. Backgrounds
  {
    id: "bg-astra-dark-grid",
    name: "Astra 3D Sheared Grid Floor Plate",
    type: "background",
    whatItCommunicates: "An institutional market trading floor; vast, structured, and endlessly scalable.",
    creativeProblemSolved: "How to anchor floating 3D cards and mockups so they do not feel like they are floating in an empty black void.",
    emotionalEffect: ["tension", "precision", "hyper-focus"],
    compatibleStyles: ["dark-saas", "fintech-flow", "cyber-terminal"],
    compatibleCompositions: ["perspective-card-grid", "monolithic-vertical", "asymmetric-grid"],
    usefulCombinations: ["tech-conveyor-belt-3d", "ref-astra-prediction-conveyor", "sound-sub-tension-drone"],
    parameters: {
      gridOpacity: 0.28,
      vignetteDepth: 0.65,
      horizonFadeStartPercent: 62,
    },
    knownFailureModes: [
      "Collides with dark grey cards if card border is not explicitly set to >= #334155",
      "Do not use with editorial light brands or serif typography",
    ],
    previewOrExample: {
      referenceFile: "public/assets/backgrounds/astra-dark-grid-plate.png",
      description: "Deep perspective 3D grid with dark obsidian gradient floor extracted from Astra broadcast reference.",
    },
    qualityScore: 9.8,
    tags: ["background", "grid", "astra", "dark", "fintech", "plate"],
    provenIn: "Astra / Hedge Motion Benchmark (Act 1: Endless manual prediction tasks)",
  },
  {
    id: "bg-astra-horizon-glow",
    name: "Astra Amber Horizon Event Bloom",
    type: "background",
    whatItCommunicates: "High-stakes financial threshold; dawn of market opportunity and intense liquidity.",
    creativeProblemSolved: "How to inject warm emotional color into a cold dark fintech ad without looking like a rainbow gimmick.",
    emotionalEffect: ["awe", "urgency", "prestige"],
    compatibleStyles: ["fintech-flow", "dark-saas"],
    compatibleCompositions: ["monumental-centered", "wide-cinematic", "asymmetric-editorial"],
    usefulCombinations: ["ref-astra-dark-web-platform", "typo-monumental-clean-sans", "ui-badge-prediction-market"],
    parameters: {
      bloomColor: "#F59E0B",
      bloomIntensity: 0.35,
      verticalCenterY: 78,
    },
    knownFailureModes: [
      "Bleeds out white text if text is placed directly over the amber horizon (maintain text Y <= 40%)",
      "Overwhelms cool cyan or green brand accents if not tinted accordingly",
    ],
    previewOrExample: {
      referenceFile: "public/assets/backgrounds/astra-horizon-glow.png",
      description: "Warm amber horizon atmospheric bloom extracted from Astra Climax sequence.",
    },
    qualityScore: 9.9,
    tags: ["background", "amber", "bloom", "horizon", "astra", "prestige"],
    provenIn: "Astra Reference Climax (00:14)",
  },
  {
    id: "bg-blinkcash-cyan-ambient",
    name: "BlinkCash Cyan Ambient Velocity Plate",
    type: "background",
    whatItCommunicates: "Effortless liquidity; crisp, modern, ultra-reliable digital cash movement.",
    creativeProblemSolved: "How to make financial transactions feel clean, safe, and lightning fast.",
    emotionalEffect: ["delight", "relief", "precision"],
    compatibleStyles: ["fintech-flow", "cyber-terminal", "minimalist"],
    compatibleCompositions: ["monolithic-vertical", "asymmetric-editorial"],
    usefulCombinations: ["ref-blinkcash-stablecoin-deposit", "ui-badge-usdc-verified", "sound-warm-resolution-chime"],
    parameters: {
      ambientCyanHex: "#06B6D4",
      vignetteDarkness: 0.45,
      radialFalloffPx: 720,
    },
    knownFailureModes: [
      "Avoid red warning badges on cyan background (creates jarring vibration)",
      "Do not combine with chaotic heavy grit film grain",
    ],
    previewOrExample: {
      referenceFile: "public/assets/backgrounds/blinkcash-cyan-ambient.png",
      description: "Electric cyan ambient fintech backdrop extracted from BlinkCashX broadcast video.",
    },
    qualityScore: 9.7,
    tags: ["background", "cyan", "fintech", "blinkcash", "liquidity"],
    provenIn: "BlinkCashX Broadcast Motion Benchmark (00:02)",
  },
  {
    id: "bg-supercool-bento-glass",
    name: "SuperCool Frosted Bento Backdrop",
    type: "background",
    whatItCommunicates: "Architectural software modularity; every capability perfectly compartmentalized.",
    creativeProblemSolved: "How to showcase multiple complementary features simultaneously without cognitive overload.",
    emotionalEffect: ["precision", "delight", "relief"],
    compatibleStyles: ["dark-saas", "fintech-flow"],
    compatibleCompositions: ["bento-grid", "cascade-stack"],
    usefulCombinations: ["tex-glass-frosted-refraction", "tech-action-progress-modal", "sound-tactile-mechanical-switch"],
    parameters: {
      backdropBlurPx: 28,
      cardBorderLuminance: 0.12,
      specularReflectionAngle: 45,
    },
    knownFailureModes: [
      "Never put more than 4 primary bento tiles in a vertical 9:16 aspect ratio",
      "Ensure body copy within bento tiles does not exceed 3 lines",
    ],
    previewOrExample: {
      referenceFile: "public/assets/backgrounds/supercool-bento-glass.png",
      description: "Frosted bento glass card layout extracted from SuperCool launch video.",
    },
    qualityScore: 9.8,
    tags: ["background", "bento", "glass", "modular", "launch"],
    provenIn: "We make super cool launch videos (00:04)",
  },
  {
    id: "bg-monolithic-graphite",
    name: "Monolithic Studio Graphite Dark Void",
    type: "background",
    whatItCommunicates: "Industrial supremacy; heavy engineered precision with zero digital superficiality.",
    creativeProblemSolved: "How to present hardware or deep-tech developer infrastructure with monumental weight.",
    emotionalEffect: ["precision", "prestige", "hyper-focus"],
    compatibleStyles: ["industrial-craft", "dark-saas", "minimalist"],
    compatibleCompositions: ["monumental-centered", "monolithic-vertical", "macro-extreme"],
    usefulCombinations: ["tech-pbr-titanium-pivot", "device-ipad-pro-m4", "sound-impact"],
    parameters: {
      graphiteHex: "#111215",
      specularSheenIntensity: 0.18,
      rimLightingAngle: 315,
    },
    knownFailureModes: [
      "Requires high-contrast white/silver typography (#F8FAFC) to avoid muddy readability",
      "Avoid bouncy spring physics (must use overdamped or linear easing)",
    ],
    previewOrExample: {
      referenceFile: "public/assets/backgrounds/monolithic-graphite-dark.png",
      description: "Studio matte graphite dark surface plate extracted from 84-hour motion piece.",
    },
    qualityScore: 9.9,
    tags: ["background", "graphite", "monolith", "hardware", "precision"],
    provenIn: "84 Hours No AI Benchmark (00:03)",
  },
  {
    id: "bg-kinetic-stream-lines",
    name: "Kinetic Velocity Stream Lines",
    type: "background",
    whatItCommunicates: "Blistering runtime throughput; warp-speed computation and immediate execution.",
    creativeProblemSolved: "How to communicate speed and performance metrics without resorting to boring static line graphs.",
    emotionalEffect: ["urgency", "awe", "delight"],
    compatibleStyles: ["cyber-terminal", "dark-saas"],
    compatibleCompositions: ["diagonal-shear", "perspective-card-grid"],
    usefulCombinations: ["tech-metric-surge", "ui-badge-latency-ultra", "sound-whoosh"],
    parameters: {
      streamVelocity: 8.5,
      streakCount: 36,
      streakColor: "#38BDF8",
    },
    knownFailureModes: [
      "Streak velocity over 12 px/frame triggers motion blur nausea",
      "Never layer dense paragraphs over kinetic stream lines",
    ],
    previewOrExample: {
      referenceFile: "public/assets/backgrounds/kinetic-stream-lines.png",
      description: "High-energy kinetic motion stream lines with directional blur.",
    },
    qualityScore: 9.6,
    tags: ["background", "velocity", "stream", "speed", "kinetic"],
    provenIn: "Best thing you'll see today (00:05)",
  },

  // 2. Textures & Overlays
  {
    id: "tex-glass-frosted-refraction",
    name: "Refractive Frosted Glass Surface",
    type: "component",
    whatItCommunicates: "Tangible depth, optical refraction, and multi-layered UI sophisticated elegance.",
    creativeProblemSolved: "How to give flat 2D cards authentic tactile optical presence.",
    emotionalEffect: ["delight", "prestige"],
    compatibleStyles: ["dark-saas", "fintech-flow"],
    compatibleCompositions: ["bento-grid", "cascade-stack"],
    usefulCombinations: ["bg-supercool-bento-glass", "tech-dof-floating-cards"],
    parameters: {
      refractionBlurPx: 24,
      innerHighlightOpacity: 0.15,
      borderSpecularWidthPx: 1,
    },
    knownFailureModes: [
      "Heavy performance impact if applied to more than 6 active elements simultaneously",
    ],
    previewOrExample: {
      referenceFile: "public/assets/textures/glass-frosted-refraction.png",
      description: "High-resolution frosted glass optical dispersion texture.",
    },
    qualityScore: 9.7,
    tags: ["texture", "glass", "refraction", "frosted", "bento"],
    provenIn: "Super Cool Launch Videos (00:10)",
  },
  {
    id: "tex-specular-lens-flare",
    name: "Anamorphic Specular Flare Ray",
    type: "component",
    whatItCommunicates: "Cinematic lighting polish; premium optical lens flare glancing off metallic edges.",
    creativeProblemSolved: "How to direct viewer eye tracking to a critical CTA button or key metric reveal.",
    emotionalEffect: ["awe", "prestige"],
    compatibleStyles: ["dark-saas", "industrial-craft", "fintech-flow"],
    compatibleCompositions: ["monumental-centered", "monolithic-vertical"],
    usefulCombinations: ["tech-pbr-titanium-pivot", "tech-kinetic-glow-punch", "sound-riser"],
    parameters: {
      flareWidthPx: 480,
      flareAngleDeg: -25,
      blendMode: "screen",
    },
    knownFailureModes: [
      "Avoid centering flare over paragraphs (causes localized illegibility)",
    ],
    previewOrExample: {
      referenceFile: "public/assets/textures/specular-lens-flare.png",
      description: "Clean anamorphic specular flare ray texture extracted from 84-hour motion piece.",
    },
    qualityScore: 9.8,
    tags: ["texture", "flare", "specular", "anamorphic", "cinematic"],
    provenIn: "84 Hours No AI Benchmark (00:08)",
  },

  // 3. UI Micro-Components & Badges
  {
    id: "ui-badge-usdc-verified",
    name: "Instant USDC Settlement Pill",
    type: "component",
    whatItCommunicates: "Instant, cryptographic, fully reserved dollar settlement on-chain.",
    creativeProblemSolved: "How to prove enterprise crypto credibility and security in a single micro-badge.",
    emotionalEffect: ["precision", "relief"],
    compatibleStyles: ["fintech-flow", "dark-saas"],
    compatibleCompositions: ["monolithic-vertical", "asymmetric-editorial"],
    usefulCombinations: ["bg-blinkcash-cyan-ambient", "ref-blinkcash-stablecoin-deposit", "sound-warm-resolution-chime"],
    parameters: {
      badgeWidthPx: 280,
      pillHeightPx: 64,
      statusDotColor: "#10B981",
    },
    knownFailureModes: [
      "Never display adjacent to unverified speculative token symbols",
    ],
    previewOrExample: {
      referenceFile: "public/assets/ui/badge-usdc-verified.svg",
      description: "Verified USDC Settlement badge with security glow.",
    },
    qualityScore: 9.8,
    tags: ["ui", "badge", "usdc", "fintech", "stablecoin"],
    provenIn: "BlinkCashX Mobile Deposit Sequence",
  },
  {
    id: "ui-badge-latency-ultra",
    name: "Sub-12ms Latency Execution Pill",
    type: "component",
    whatItCommunicates: "Absolute speed advantage; sub-frame execution latency leaving legacy systems behind.",
    creativeProblemSolved: "How to visualize API/network performance without a full technical dashboard.",
    emotionalEffect: ["urgency", "precision"],
    compatibleStyles: ["cyber-terminal", "dark-saas", "fintech-flow"],
    compatibleCompositions: ["diagonal-shear", "perspective-card-grid"],
    usefulCombinations: ["bg-kinetic-stream-lines", "tech-metric-surge", "sound-whoosh"],
    parameters: {
      badgeWidthPx: 260,
      pillHeightPx: 56,
      accentGreenHex: "#22C55E",
    },
    knownFailureModes: [
      "Do not place near red urgency badges (causes green/red traffic-light confusion)",
    ],
    previewOrExample: {
      referenceFile: "public/assets/ui/badge-latency-ultra.svg",
      description: "Ultra-low latency execution pill (<12ms) with directional trend arrow.",
    },
    qualityScore: 9.7,
    tags: ["ui", "badge", "latency", "speed", "performance"],
    provenIn: "High-Frequency Trading & Velocity Benchmarks",
  },
  {
    id: "ui-badge-prediction-market",
    name: "Astra Live Event Probability Pill",
    type: "component",
    whatItCommunicates: "Real-time crowd intelligence and predictive market odds updating live.",
    creativeProblemSolved: "How to showcase dynamic betting or prediction probabilities with crystal clarity.",
    emotionalEffect: ["tension", "urgency", "awe"],
    compatibleStyles: ["fintech-flow", "dark-saas"],
    compatibleCompositions: ["perspective-card-grid", "asymmetric-grid"],
    usefulCombinations: ["bg-astra-horizon-glow", "ref-astra-prediction-conveyor", "sound-tension-drone"],
    parameters: {
      badgeWidthPx: 340,
      pillHeightPx: 72,
      probabilityText: "84.2% YES",
      deltaBadgeText: "+14.6%",
    },
    knownFailureModes: [
      "Text clipping if event headline exceeds 28 characters",
    ],
    previewOrExample: {
      referenceFile: "public/assets/ui/badge-prediction-market.svg",
      description: "Astra-style live probability market pill with dynamic amber odds indicator.",
    },
    qualityScore: 9.9,
    tags: ["ui", "badge", "prediction", "odds", "astra", "fintech"],
    provenIn: "Astra Prediction Reference (Frame 365)",
  },
  {
    id: "ui-card-transaction-success",
    name: "Instant Verified Settlement Receipt",
    type: "component",
    whatItCommunicates: "Zero-friction finality; the absolute catharsis of a completed high-value action.",
    creativeProblemSolved: "How to deliver the payoff moment in a conversion ad.",
    emotionalEffect: ["relief", "delight", "precision"],
    compatibleStyles: ["fintech-flow", "dark-saas", "cyber-terminal"],
    compatibleCompositions: ["monolithic-vertical", "asymmetric-editorial"],
    usefulCombinations: ["bg-blinkcash-cyan-ambient", "tech-action-progress-modal", "sound-warm-resolution-chime"],
    parameters: {
      cardWidthPx: 420,
      cardHeightPx: 180,
      settlementSpeedLabel: "0.14s",
      settlementAmount: "$10,000.00 USDC",
    },
    knownFailureModes: [
      "Never place higher than Y:60% in a mobile lockup (phone screen must anchor the upper frame)",
    ],
    previewOrExample: {
      referenceFile: "public/assets/ui/card-transaction-success.svg",
      description: "Fintech instant transaction verified settlement receipt card.",
    },
    qualityScore: 9.8,
    tags: ["ui", "card", "receipt", "settlement", "fintech", "catharsis"],
    provenIn: "BlinkCashX Payoff Climax",
  },

  // 4. Hardware Devices
  {
    id: "device-ipad-pro-m4",
    name: "iPad Pro M4 Ultra-Thin Vector Chassis",
    type: "3d-model",
    whatItCommunicates: "Pro-level tablet canvas; extreme power in an impossibly thin form factor.",
    creativeProblemSolved: "How to showcase tablet-optimized workflows and creative apps without generic 3D asset bloat.",
    emotionalEffect: ["precision", "prestige"],
    compatibleStyles: ["dark-saas", "industrial-craft", "editorial-light"],
    compatibleCompositions: ["wide-cinematic", "asymmetric-grid"],
    usefulCombinations: ["bg-monolithic-graphite", "tech-pbr-titanium-pivot"],
    parameters: {
      bezelWidthPx: 16,
      cornerRadiusPx: 36,
      chassisGradient: "linear-gradient(135deg, #2D2F35, #1A1C20, #121316)",
    },
    knownFailureModes: [
      "In vertical 9:16 ads, iPad frame must be scaled to fit canvas width <= 92%",
    ],
    previewOrExample: {
      referenceFile: "public/assets/devices/ipad-pro-m4-frame.svg",
      description: "iPad Pro M4 ultra-thin vector hardware frame with micro-bezels.",
    },
    qualityScore: 9.8,
    tags: ["device", "ipad", "hardware", "vector", "tablet"],
    provenIn: "Apple Pro Studio Workflows",
  },
  {
    id: "device-studio-display-5k",
    name: "Studio Display 5K Aluminum Frame",
    type: "3d-model",
    whatItCommunicates: "Desktop mastery; the ultimate professional workspace and crystal-clear visibility.",
    creativeProblemSolved: "How to frame complex desktop software apps with premium hardware framing.",
    emotionalEffect: ["precision", "prestige"],
    compatibleStyles: ["dark-saas", "industrial-craft", "editorial-light"],
    compatibleCompositions: ["monumental-centered", "wide-cinematic"],
    usefulCombinations: ["bg-monolithic-graphite", "sound-impact"],
    parameters: {
      aspectRatio: "16:9",
      aluminumStandHeightPx: 220,
      panelWidthPx: 1480,
    },
    knownFailureModes: [
      "Stand foot will clip off-canvas if vertical offset Y > 50%",
    ],
    previewOrExample: {
      referenceFile: "public/assets/devices/studio-display-5k-frame.svg",
      description: "Studio Display 5K monitor frame with aluminum stand.",
    },
    qualityScore: 9.7,
    tags: ["device", "monitor", "desktop", "hardware", "display"],
    provenIn: "Studio Workstation Workflows",
  },

  // 5. Broadcast Audio Sound Cues
  {
    id: "sound-warm-resolution-chime",
    name: "Warm Harmonic Resolution Chime (880Hz)",
    type: "sound-cue",
    whatItCommunicates: "Relief, achievement, instant settlement, and emotional gratification.",
    creativeProblemSolved: "How to sonically reward the viewer when a problem is solved or transaction clears.",
    emotionalEffect: ["relief", "delight"],
    compatibleStyles: ["fintech-flow", "dark-saas", "editorial-light", "minimalist"],
    compatibleCompositions: ["monolithic-vertical", "asymmetric-editorial", "bento-grid"],
    usefulCombinations: ["ui-card-transaction-success", "tech-action-progress-modal", "bg-blinkcash-cyan-ambient"],
    parameters: {
      fundamentalHz: 880,
      decaySeconds: 1.2,
      harmonicsCount: 4,
    },
    knownFailureModes: [
      "Do not trigger during high-stress problem scene; reserve exclusively for resolution/payoff scene",
    ],
    previewOrExample: {
      referenceFile: "public/audio/sfx/chime.wav",
      description: "Rich 880Hz harmonic metallic bell settlement chime synthesized with pure PCM audio.",
    },
    qualityScore: 9.9,
    tags: ["audio", "sfx", "chime", "resolution", "relief", "settlement"],
    provenIn: "BlinkCashX Settlement Climax",
  },
  {
    id: "sound-sub-tension-drone",
    name: "Resonant Sub-Bass Tension Drone (48Hz)",
    type: "sound-cue",
    whatItCommunicates: "Dread, overwhelming stakes, heavy impending friction, and intense focus.",
    creativeProblemSolved: "How to instantly build visceral tension in the opening 2 seconds without loud harsh noise.",
    emotionalEffect: ["tension", "visual-overload", "urgency"],
    compatibleStyles: ["dark-saas", "fintech-flow", "cyber-terminal"],
    compatibleCompositions: ["perspective-card-grid", "diagonal-shear"],
    usefulCombinations: ["bg-astra-dark-grid", "ref-astra-prediction-conveyor", "tech-conveyor-belt-3d"],
    parameters: {
      droneHz: 48,
      lfoRateHz: 0.8,
      durationSeconds: 2.0,
    },
    knownFailureModes: [
      "Never play simultaneously with loud melodic music bassline (causes phase cancellation muddiness)",
    ],
    previewOrExample: {
      referenceFile: "public/audio/sfx/tension-drone.wav",
      description: "Deep 48Hz resonant sub-bass drone with slow 0.8Hz breathing LFO envelope.",
    },
    qualityScore: 9.8,
    tags: ["audio", "sfx", "drone", "tension", "sub-bass", "urgency"],
    provenIn: "Astra Act 1 Opening Drone",
  },
  {
    id: "sound-tactile-mechanical-switch",
    name: "Tactile Mechanical Switch Keystroke",
    type: "sound-cue",
    whatItCommunicates: "Physical tactile precision, immediate human command, and keyboard-first speed.",
    creativeProblemSolved: "How to make software UI interactions feel deeply satisfying and physical.",
    emotionalEffect: ["precision", "delight"],
    compatibleStyles: ["dark-saas", "cyber-terminal", "industrial-craft"],
    compatibleCompositions: ["bento-grid", "monolithic-vertical"],
    usefulCombinations: ["tech-bezier-cursor-interaction", "bg-supercool-bento-glass"],
    parameters: {
      primaryClickHz: 3200,
      bottomOutHz: 1800,
      splitMs: 8,
    },
    knownFailureModes: [
      "Avoid machine-gun repetition (<50ms apart) which sounds like audio corruption",
    ],
    previewOrExample: {
      referenceFile: "public/audio/sfx/switch.wav",
      description: "Dual-transient mechanical switch keystroke click with tactile bottom-out.",
    },
    qualityScore: 9.8,
    tags: ["audio", "sfx", "switch", "click", "tactile", "keystroke"],
    provenIn: "Super Cool Launch UI Interactions",
  },
];
