import { CreativeMemoryItem } from "../types";

export const CATHARTIC_RELIEF_ITEMS: CreativeMemoryItem[] = [
  {
    id: "comp-uncluttered-bento",
    name: "Uncluttered Bento Workspace",
    type: "composition",
    whatItCommunicates: "Chaos brought to total order; every workflow neatly contained and automated.",
    creativeProblemSolved: "How to transition from chaotic problem states into an organized, deeply satisfying interface showcase.",
    emotionalEffect: ["relief", "delight", "precision"],
    compatibleStyles: ["dark-saas", "fintech-flow", "minimalist"],
    compatibleCompositions: ["wide-cinematic", "asymmetric-editorial"],
    usefulCombinations: ["tech-snappy-card-drop", "tech-action-progress-modal", "bg-clean-slate-fade", "sound-chime-relief", "trans-slide-left"],
    parameters: {
      columns: 3,
      gapPx: 16,
      cardBorderRadius: 18,
      negativeSpaceRatio: 0.48,
    },
    knownFailureModes: [
      "Filling all bento cells with dense text destroys the sense of relief (keep 1 cell purely visual/metric)",
      "Card clipping if overall bento width > 90% on mobile 9:16 aspect ratio",
    ],
    previewOrExample: {
      codeSnippet: "<BentoGrid cards={solutionPanels} stagger={6} />",
      description: "Harmonious 3-column glassmorphic bento grid settling into place with smooth spring eases.",
    },
    qualityScore: 9.6,
    tags: ["bento", "relief", "order", "clean", "workspace"],
  },
  {
    id: "tech-snappy-card-drop",
    name: "Snappy Bezier Drop-In Settlement",
    type: "motion-technique",
    whatItCommunicates: "Decisive solution falling into place; effortless resolution of friction.",
    creativeProblemSolved: "How to animate interface components entering the screen with crisp, satisfying weight.",
    emotionalEffect: ["relief", "delight"],
    compatibleStyles: ["dark-saas", "fintech-flow", "cyber-terminal"],
    compatibleCompositions: ["wide-cinematic", "monolithic-vertical"],
    usefulCombinations: ["comp-uncluttered-bento", "sound-chime-relief"],
    parameters: {
      bezierCurve: [0.16, 1.0, 0.3, 1.0],
      overshootPercent: 3.5,
      staggerDelayFrames: 6,
    },
    knownFailureModes: [
      "Too much overshoot (> 8%) feels cartoonish instead of professional SaaS",
    ],
    previewOrExample: {
      codeSnippet: "transform: `translateY(${interpolate(progress, [0, 1], [-80, 0], { easing: Easing.bezier(0.16, 1.0, 0.3, 1.0) })}px)`;",
    },
    qualityScore: 9.7,
    tags: ["card-drop", "snappy", "bezier", "settle", "relief"],
    provenIn: "Linear High-Craft Benchmark Scene 2",
  },
  {
    id: "tech-action-progress-modal",
    name: "Spring-Loaded Progress Ring & Checkmark Pop",
    type: "motion-technique",
    whatItCommunicates: "Instant autonomous completion; the machine doing the work in milliseconds.",
    creativeProblemSolved: "How to visually prove that a complex process completed instantly without boring loading spinners.",
    emotionalEffect: ["relief", "delight", "precision"],
    compatibleStyles: ["dark-saas", "fintech-flow", "industrial-craft"],
    compatibleCompositions: ["monolithic-vertical", "asymmetric-grid"],
    usefulCombinations: ["comp-uncluttered-bento", "sound-chime-relief"],
    parameters: {
      ringFillDurationFrames: 18,
      checkmarkPopFrame: 22,
      particleBurst: true,
    },
    knownFailureModes: [
      "Checkmark popping too late (> 35 frames) slows down ad pacing",
    ],
    previewOrExample: {
      description: "Luminous circular progress ring fills in 18 frames, bursting into a crisp neon checkmark with micro-sparks.",
    },
    qualityScore: 9.5,
    tags: ["progress", "modal", "checkmark", "success", "relief"],
  },
  {
    id: "bg-clean-slate-fade",
    name: "Subtle Studio Slate with Deep Cyan Aura",
    type: "background",
    whatItCommunicates: "Calm after the storm; breathing room; enterprise stability.",
    creativeProblemSolved: "How to shift atmosphere from danger/friction to confidence and clarity.",
    emotionalEffect: ["relief", "precision"],
    compatibleStyles: ["dark-saas", "fintech-flow", "minimalist"],
    compatibleCompositions: ["wide-cinematic", "asymmetric-editorial"],
    usefulCombinations: ["comp-uncluttered-bento", "tech-snappy-card-drop"],
    parameters: {
      primaryColor: "#0A101D",
      gradientTo: "#0F1E36",
      auraColor: "#00D4FF18",
      angle: 135,
    },
    knownFailureModes: [
      "If cyan aura is placed in the center, it washes out white headline text",
    ],
    previewOrExample: {
      description: "Deep midnight slate gradient with soft off-center cyan luminescence.",
    },
    qualityScore: 9.4,
    tags: ["background", "slate", "cyan", "aura", "relief"],
  },
  {
    id: "typo-editorial-restrained-serif",
    name: "Restrained Editorial Serif Solution Headline",
    type: "typography-treatment",
    whatItCommunicates: "Sophisticated clarity; elevated brand maturity.",
    creativeProblemSolved: "How to introduce the solution with elegance rather than aggressive salesmanship.",
    emotionalEffect: ["relief", "prestige"],
    compatibleStyles: ["editorial-light", "dark-saas", "minimalist"],
    compatibleCompositions: ["asymmetric-editorial", "wide-cinematic"],
    usefulCombinations: ["comp-uncluttered-bento", "bg-clean-slate-fade"],
    parameters: {
      fontSize: 52,
      fontWeight: 400,
      fontFamily: "'Newsreader', 'Playfair Display', Georgia, serif",
      letterSpacing: "-0.015em",
      animation: "fade-up",
    },
    knownFailureModes: [
      "Serif typography feels jarring if the product is a hardcore developer CLI terminal",
    ],
    previewOrExample: {
      codeSnippet: "<KineticText text='One unified platform for modern treasury.' serifFont={true} />",
    },
    qualityScore: 9.6,
    tags: ["typography", "serif", "editorial", "restraint", "relief"],
  },
  {
    id: "sound-chime-relief",
    name: "Harmonic Warm Resolution Chime",
    type: "sound-cue",
    whatItCommunicates: "Instantaneous success; friction dissolving into harmony.",
    creativeProblemSolved: "How to give the ear a psychological sense of relief when the product arrives.",
    emotionalEffect: ["relief", "delight"],
    compatibleStyles: ["dark-saas", "fintech-flow", "editorial-light"],
    compatibleCompositions: ["all"],
    usefulCombinations: ["tech-action-progress-modal", "comp-uncluttered-bento"],
    parameters: {
      rootNote: "Eb",
      warmReverbDecaySec: 1.8,
      volume: 0.75,
    },
    knownFailureModes: [
      "Sounds like a generic elevator chime if reverb decay is less than 0.8s",
    ],
    previewOrExample: {
      description: "Warm, rich musical chord resolving the low-frequency tension rumble.",
    },
    qualityScore: 9.7,
    tags: ["audio", "chime", "harmony", "resolution", "relief"],
  },
];
