import { CreativeMemoryItem } from "../types";

export const EDITORIAL_LUXURY_ITEMS: CreativeMemoryItem[] = [
  {
    id: "comp-editorial-manifesto",
    name: "Quiet Editorial Manifesto Print Layout",
    type: "composition",
    whatItCommunicates: "Timeless luxury, sensory sanctuary, intellectual sophistication, zero synthetic noise.",
    creativeProblemSolved: "How to advertise high-end apothecary, luxury goods, or architectural products without looking like a loud hyperactive tech commercial.",
    emotionalEffect: ["prestige", "awe", "relief"],
    compatibleStyles: ["editorial-light", "minimalist"],
    compatibleCompositions: ["asymmetric-editorial", "monumental-centered"],
    usefulCombinations: ["tech-macro-letterspacing", "bg-editorial-sand-grain", "typo-newsreader-serif-monumental", "sound-low-warm-pad", "trans-monochrome-dissolve"],
    parameters: {
      negativeSpaceRatio: 0.64,
      paperGrainIntensity: 0.08,
      headlineMaxWidthPercent: 68,
      safeHorizontalMarginPercent: 16,
    },
    knownFailureModes: [
      "CRITICAL: If text is left-anchored at 30% with width 74%, it overflows canvas (30+74=104%). Max width must be clamped to (90 - posX)",
      "Destroyed if neon glow highlights, B2B SaaS pipeline charts, or emoji icons are introduced",
      "Do not use hyperactive spring bounces; motion must be subtle micro-holds and calm dissolves",
    ],
    previewOrExample: {
      referenceFile: "C:/Users/USER/.gemini/antigravity/brain/4a9f2cd9-0e38-4308-8594-b5d3eb044a46/aesop-scene-1.png",
      description: "Serene warm sand canvas with centered Newsreader serif statement, 64% negative space, and delicate paper texture.",
    },
    qualityScore: 9.8,
    tags: ["editorial", "luxury", "apothecary", "skincare", "manifesto", "serif"],
    provenIn: "Aesop Editorial Benchmark Scene 1 & 3",
  },
  {
    id: "tech-macro-letterspacing",
    name: "Deliberate Micro-Letterspacing Expansion",
    type: "motion-technique",
    whatItCommunicates: "Architectural stillness; words breathing into existence with regal composure.",
    creativeProblemSolved: "How to animate text in luxury advertisements without cheesy word-by-word popups or bouncing letters.",
    emotionalEffect: ["prestige", "awe"],
    compatibleStyles: ["editorial-light", "minimalist"],
    compatibleCompositions: ["asymmetric-editorial", "monumental-centered"],
    usefulCombinations: ["comp-editorial-manifesto", "bg-editorial-sand-grain"],
    parameters: {
      letterSpacingStartEm: 0.02,
      letterSpacingEndEm: 0.065,
      durationFrames: 50,
      ease: "easeOutCubic",
    },
    knownFailureModes: [
      "Excessive expansion (> 0.1em) impairs readability and looks amateurish",
    ],
    previewOrExample: {
      codeSnippet: "letterSpacing: `${interpolate(frame, [0, 50], [0.02, 0.065], { extrapolateRight: 'clamp' })}em`;",
    },
    qualityScore: 9.6,
    tags: ["letterspacing", "typography", "restraint", "luxury", "slow-motion"],
  },
  {
    id: "bg-editorial-sand-grain",
    name: "Tactile Archival Sand with Natural Paper Grain",
    type: "background",
    whatItCommunicates: "Physical heritage, tactile paper, organic purity.",
    creativeProblemSolved: "How to design a light-mode advertisement that doesn't look like an unstyled white Google Doc or blinding medical sterile sheet.",
    emotionalEffect: ["prestige", "relief"],
    compatibleStyles: ["editorial-light", "minimalist"],
    compatibleCompositions: ["all"],
    usefulCombinations: ["comp-editorial-manifesto", "typo-newsreader-serif-monumental"],
    parameters: {
      primaryColor: "#F8F7F3",
      gradientTo: "#F1EFE9",
      grainAssetUrl: "assets/overlays/film-grain-35mm-tile.svg",
      vignetteStrength: 0.22,
    },
    knownFailureModes: [
      "Grain opacity > 0.15 creates dirty pixel noise rather than refined tactile paper texture",
    ],
    previewOrExample: {
      description: "Warm linen sand background plate with gentle ambient center elevation and 35mm micro-grain.",
    },
    qualityScore: 9.7,
    tags: ["background", "sand", "paper", "grain", "editorial", "luxury"],
  },
  {
    id: "typo-newsreader-serif-monumental",
    name: "Newsreader Archival Serif Monumental Typography",
    type: "typography-treatment",
    whatItCommunicates: "Poetic clarity, timeless intellect, uncompromising sensory standards.",
    creativeProblemSolved: "How to craft headline typography that commands instant respect without shouting.",
    emotionalEffect: ["prestige", "awe"],
    compatibleStyles: ["editorial-light", "minimalist"],
    compatibleCompositions: ["monumental-centered", "asymmetric-editorial"],
    usefulCombinations: ["comp-editorial-manifesto", "bg-editorial-sand-grain"],
    parameters: {
      fontSize: 54,
      fontWeight: 400,
      fontFamily: "'Newsreader', 'Playfair Display', Georgia, serif",
      color: "#1E221E",
      lineHeight: 1.35,
    },
    knownFailureModes: [
      "Never use bold heavy weights (> 500) for luxury serifs — it ruins the delicate stroke modulation",
    ],
    previewOrExample: {
      codeSnippet: "<KineticText text='Formulations crafted for those who demand quiet sensory elevation.' serifFont={true} />",
    },
    qualityScore: 9.8,
    tags: ["typography", "serif", "newsreader", "luxury", "intellect"],
    provenIn: "Aesop Editorial Benchmark",
  },
  {
    id: "sound-low-warm-pad",
    name: "Understated Analogue Acoustic Atmosphere",
    type: "sound-cue",
    whatItCommunicates: "Tranquil stillness; entering an architectural sanctuary.",
    creativeProblemSolved: "How to sonically support quiet luxury without upbeat EDM or corporate tech synth arpeggios.",
    emotionalEffect: ["prestige", "relief"],
    compatibleStyles: ["editorial-light", "minimalist"],
    compatibleCompositions: ["comp-editorial-manifesto"],
    usefulCombinations: ["comp-editorial-manifesto", "bg-editorial-sand-grain"],
    parameters: {
      warmthHz: 280,
      reverbSpace: "cathedral-chamber",
      gain: -14,
    },
    knownFailureModes: [
      "Sudden loud hits or synth sweeps ruin the contemplative atmosphere",
    ],
    previewOrExample: {
      description: "Deep analogue cello / acoustic pad hold with delicate air breath.",
    },
    qualityScore: 9.5,
    tags: ["audio", "pad", "analogue", "warmth", "sanctuary"],
  },
];
