import { CreativeMemoryItem } from "../types";

export const KINETIC_VELOCITY_ITEMS: CreativeMemoryItem[] = [
  {
    id: "comp-velocity-speedrun",
    name: "Keyboard-First Velocity Speedrun",
    type: "composition",
    whatItCommunicates: "Inhuman execution speed; power users never taking their hands off the keyboard.",
    creativeProblemSolved: "How to showcase lightning-fast dev tools and command palettes without losing the audience in blurred text.",
    emotionalEffect: ["urgency", "delight", "hyper-focus"],
    compatibleStyles: ["cyber-terminal", "dark-saas", "broadcast-bold"],
    compatibleCompositions: ["wide-cinematic", "asymmetric-grid"],
    usefulCombinations: ["tech-bezier-cursor-interaction", "tech-metric-surge", "bg-cyber-obsidian-glow", "typo-kinetic-glow-punch", "sound-fast-swoosh"],
    parameters: {
      actionIntervalFrames: 10,
      activeCardGlowIntensity: 0.8,
      hotkeyBadgeColor: "#FF6363",
    },
    knownFailureModes: [
      "If actions cycle faster than 8 frames per step, viewer cannot perceive what happened",
      "Overcrowding with secondary tooltips makes the command palette feel messy",
    ],
    previewOrExample: {
      codeSnippet: "<AppWindow mockType='custom' url='raycast.com/store' codeSnippet={scriptExecution} />",
      description: "Floating command palette cycling script extensions at 10-frame intervals with crisp active selection rings.",
    },
    qualityScore: 9.7,
    tags: ["velocity", "speedrun", "command-palette", "keyboard", "power-user"],
    provenIn: "Raycast Speedrun Benchmark Scene 2",
  },
  {
    id: "tech-bezier-cursor-interaction",
    name: "Cubic Bezier Pointer Trajectory with Spring Click",
    type: "motion-technique",
    whatItCommunicates: "Effortless, human-like interaction choreography; decisive action triggering instant automation.",
    creativeProblemSolved: "How to make automated software clicks look natural and intentional rather than robotic straight-line interpolations.",
    emotionalEffect: ["delight", "precision"],
    compatibleStyles: ["dark-saas", "fintech-flow", "cyber-terminal"],
    compatibleCompositions: ["wide-cinematic", "monolithic-vertical"],
    usefulCombinations: ["comp-velocity-speedrun", "sound-fast-swoosh"],
    parameters: {
      startPoint: { x: 20, y: 85 },
      endPoint: { x: 62, y: 48 },
      controlPoint1: { x: 38, y: 55 },
      clickAtFrame: 28,
      rippleMaxRadiusPx: 44,
      cursorSqueezeScale: 0.86,
    },
    knownFailureModes: [
      "Cursor target coordinates must align with an actual interactive button or tab, never dead space",
      "Do not display an 'AI' label pill hovering behind the cursor unless the ad is explicitly an autonomous agent showcase",
    ],
    previewOrExample: {
      codeSnippet: "<CursorInteraction from={{ x: 20, y: 85 }} to={{ x: 62, y: 48 }} clickAtFrame={28} clickRipple={true} />",
    },
    qualityScore: 9.8,
    tags: ["cursor", "bezier", "click", "ripple", "interaction"],
    provenIn: "Astra / Hedge Benchmark (Act 4: 1-Tap Execution)",
  },
  {
    id: "tech-metric-surge",
    name: "Spring-Damped Metric Counter Surge",
    type: "motion-technique",
    whatItCommunicates: "Quantifiable, verified superiority (10x faster, 99.999% uptime, 0ms latency).",
    creativeProblemSolved: "How to make numbers feel monumental and thrilling rather than boring spreadsheet statistics.",
    emotionalEffect: ["awe", "urgency", "precision"],
    compatibleStyles: ["dark-saas", "cyber-terminal", "fintech-flow"],
    compatibleCompositions: ["monumental-centered", "radial-bloom"],
    usefulCombinations: ["comp-velocity-speedrun", "bg-cyber-obsidian-glow"],
    parameters: {
      springDamping: 14,
      springStiffness: 120,
      trendArrowDelayFrames: 18,
      suffixGlow: true,
    },
    knownFailureModes: [
      "CRITICAL: Center-anchored counter (Y:50%) collides violently with centered headlines if headline is also at Y:50%. Always place headline at Y:22% and counter at Y:52%",
    ],
    previewOrExample: {
      codeSnippet: "<MetricCounter value={100} suffix='x' label='DAILY ACTIONS FIRED' trendBadge='4.8x Faster' />",
    },
    qualityScore: 9.6,
    tags: ["metric", "counter", "surge", "spring", "quantitative"],
    provenIn: "Raycast Benchmark Scene 3",
  },
  {
    id: "bg-cyber-obsidian-glow",
    name: "Cyber Obsidian with Electric Laser Rim",
    type: "background",
    whatItCommunicates: "Terminal-grade dark mode; high velocity power-user environment.",
    creativeProblemSolved: "How to make a deep black background feel electrified and modern.",
    emotionalEffect: ["urgency", "hyper-focus"],
    compatibleStyles: ["cyber-terminal", "dark-saas"],
    compatibleCompositions: ["all"],
    usefulCombinations: ["comp-velocity-speedrun", "typo-kinetic-glow-punch"],
    parameters: {
      primaryColor: "#0F1117",
      accentGlowColor: "#FF636326",
      meshPoints: 4,
    },
    knownFailureModes: [
      "Clashes with warm or pastel brand color palettes",
    ],
    previewOrExample: {
      description: "Dense obsidian canvas with localized laser rim bloom highlighting interface edges.",
    },
    qualityScore: 9.5,
    tags: ["background", "cyber", "obsidian", "electric", "dark"],
  },
  {
    id: "typo-kinetic-glow-punch",
    name: "Kinetic Word-by-Word Reveal with Blooming Glow Punch",
    type: "typography-treatment",
    whatItCommunicates: "Maximum verbal velocity; punchy cadence synced to rhythm.",
    creativeProblemSolved: "How to keep reading retention high during fast-paced ads.",
    emotionalEffect: ["urgency", "delight", "hyper-focus"],
    compatibleStyles: ["dark-saas", "cyber-terminal", "broadcast-bold"],
    compatibleCompositions: ["monumental-centered", "asymmetric-editorial"],
    usefulCombinations: ["comp-velocity-speedrun", "sound-fast-swoosh"],
    parameters: {
      staggerDelayFrames: 4,
      glowPunchKeywords: ["sub-50ms", "instant", "zero-latency", "100x"],
      bloomIntensity: 1.6,
    },
    knownFailureModes: [
      "Over-highlighting more than 2 words per sentence makes text look chaotic and uncoordinated",
    ],
    previewOrExample: {
      codeSnippet: "<KineticText text='Speed that redefines your entire day.' highlightWords={['redefines']} />",
    },
    qualityScore: 9.7,
    tags: ["typography", "kinetic", "glow-punch", "stagger", "velocity"],
  },
  {
    id: "sound-fast-swoosh",
    name: "High-Velocity Air Whoosh with Mechanical Snap",
    type: "sound-cue",
    whatItCommunicates: "Lightning-fast movement; instantaneous execution.",
    creativeProblemSolved: "How to acoustically convey extreme speed during transitions and card entrances.",
    emotionalEffect: ["urgency", "delight"],
    compatibleStyles: ["dark-saas", "cyber-terminal", "broadcast-bold"],
    compatibleCompositions: ["all"],
    usefulCombinations: ["comp-velocity-speedrun", "tech-bezier-cursor-interaction"],
    parameters: {
      whooshDurationMs: 180,
      snapPitchHz: 4400,
      volume: 0.8,
    },
    knownFailureModes: [
      "Harsh frequencies if high-pass filter is set above 8kHz",
    ],
    previewOrExample: {
      description: "Clean, aerodynamic air displacement followed by a micro-switch snap.",
    },
    qualityScore: 9.6,
    tags: ["audio", "whoosh", "swoosh", "snap", "velocity"],
  },
];
