import { CreativeMemoryItem } from "../types";

export const REFERENCE_BREAKDOWN_ITEMS: CreativeMemoryItem[] = [
  {
    id: "ref-astra-prediction-conveyor",
    name: "Astra/Hedge 3D Prediction Card Stream",
    type: "reference",
    whatItCommunicates: "Limitless live market events, real-time betting probabilities, and high-frequency trading opportunities.",
    creativeProblemSolved: "How to showcase large volume of dynamic market data in continuous motion without visual stutter.",
    emotionalEffect: ["tension", "visual-overload", "urgency"],
    compatibleStyles: ["fintech-flow", "dark-saas", "cyber-terminal"],
    compatibleCompositions: ["perspective-card-grid", "diagonal-shear"],
    usefulCombinations: ["tech-conveyor-belt-3d", "bg-tension-shear-grid", "sound-tension-hum"],
    parameters: {
      perspectiveDegrees: 45,
      columns: 2,
      cardWidthPx: 380,
      continuousScrollSpeed: 4.8,
      oddsHighlightColor: "#F59E0B",
    },
    knownFailureModes: [
      "Odds percentage text will clash with card background if contrast is < 4.5:1",
      "Overlapping cards if vertical margin gap is less than 18px",
    ],
    previewOrExample: {
      referenceFile: "c:/Users/USER/Documents/adcraft/your job/Screenshot (365).png",
      description: "Infinite cascading cards flowing downwards in 3D perspective with yellow glowing odds cards.",
    },
    qualityScore: 9.9,
    tags: ["reference", "astra", "hedge", "conveyor", "prediction-markets", "3d"],
    provenIn: "Astra Motion Reference Study (92-frame breakdown)",
  },
  {
    id: "ref-astra-phone-depth-lockup",
    name: "Astra/Hedge 3D Phone with Background Kinetic Typography",
    type: "reference",
    whatItCommunicates: "Unrivaled mobile leverage; high-stakes financial power at your fingertips.",
    creativeProblemSolved: "How to combine a physical mobile device mockup with massive typography without having the phone completely block the words.",
    emotionalEffect: ["precision", "awe", "urgency"],
    compatibleStyles: ["fintech-flow", "dark-saas", "industrial-craft"],
    compatibleCompositions: ["monolithic-vertical", "asymmetric-grid"],
    usefulCombinations: ["tech-pbr-titanium-pivot", "bg-matte-graphite-specular", "typo-monumental-clean-sans"],
    parameters: {
      phoneXPercent: 42,
      backgroundTextXPercent: 72,
      backgroundTextFontSize: 92,
      backgroundTextZIndex: -10,
    },
    knownFailureModes: [
      "CRITICAL: If phone is placed directly at center (X:50%), background typography is 70% occluded and illegible. Always offset phone to X:38-44% and text to X:68-76%",
    ],
    previewOrExample: {
      referenceFile: "c:/Users/USER/Documents/adcraft/your job/Screenshot (388).png",
      description: "iPhone 16 Pro mockup showing live market UI with massive kinetic text 'the leverage' floating behind it on Z-depth plane.",
    },
    qualityScore: 9.9,
    tags: ["reference", "astra", "phone-mockup", "typography-layering", "depth"],
    provenIn: "Astra Motion Reference Study (Frame 388)",
  },
  {
    id: "ref-astra-dark-web-platform",
    name: "Astra/Hedge 3D Web Platform with Golden Glow Rim",
    type: "reference",
    whatItCommunicates: "Institutional event trading; deep liquidity and high leverage executed on desktop.",
    creativeProblemSolved: "How to make a web dashboard look cinematic, dramatic, and sleek rather than boring flat SaaS.",
    emotionalEffect: ["precision", "prestige", "hyper-focus"],
    compatibleStyles: ["fintech-flow", "dark-saas"],
    compatibleCompositions: ["wide-cinematic", "macro-extreme"],
    usefulCombinations: ["tech-dof-floating-cards", "bg-matte-graphite-specular"],
    parameters: {
      headerGlowColor: "#F59E0B66",
      perspectiveDeg: 35,
      tiltDeg: 4,
      mountainBannerTexture: true,
    },
    knownFailureModes: [
      "Golden glow rim can bleed into white chart lines if bloom blur radius > 32px",
    ],
    previewOrExample: {
      referenceFile: "c:/Users/USER/Documents/adcraft/your job/Screenshot (408).png",
      description: "Angled web app window floating in dark void with golden honey glow emanating from the top navigation bar.",
    },
    qualityScore: 9.8,
    tags: ["reference", "astra", "web-app", "golden-glow", "fintech"],
    provenIn: "Astra Motion Reference Study (Frame 408)",
  },
  {
    id: "ref-blinkcash-stablecoin-deposit",
    name: "BlinkCashX One-Tap Deposit Velocity",
    type: "reference",
    whatItCommunicates: "Frictionless global liquidity; converting cash to stablecoins in milliseconds with one tap.",
    creativeProblemSolved: "How to make financial crypto deposits feel completely safe, immediate, and as simple as sending a text message.",
    emotionalEffect: ["delight", "relief", "urgency"],
    compatibleStyles: ["fintech-flow", "cyber-terminal"],
    compatibleCompositions: ["monolithic-vertical", "asymmetric-editorial"],
    usefulCombinations: ["tech-bezier-cursor-interaction", "tech-action-progress-modal", "sound-chime-relief"],
    parameters: {
      depositAmount: "$250.00",
      settlementTimeMs: 14,
      hapticPulseDurationFrames: 8,
    },
    knownFailureModes: [
      "Must not look like a scam wallet; adhere strictly to clean corporate typography and verified lock badges",
    ],
    previewOrExample: {
      description: "One-tap mobile payment flow with animated cursor tap, expanding confirmation ripple, and instant balance update.",
    },
    qualityScore: 9.7,
    tags: ["reference", "blinkcash", "stablecoin", "fintech", "mobile", "deposit"],
    provenIn: "Motion Examples: One tap, Stablecoin deposits (BlinkCashX)",
  },
  {
    id: "ref-architectural-monolith-hook",
    name: "Stark Typographic Negative Space Hook",
    type: "reference",
    whatItCommunicates: "Unflinching confidence; commanding total silence before making an undeniable claim.",
    creativeProblemSolved: "How to start an ad with extreme emotional weight without any motion graphics clutter.",
    emotionalEffect: ["prestige", "tension", "hyper-focus"],
    compatibleStyles: ["dark-saas", "fintech-flow", "industrial-craft", "minimalist"],
    compatibleCompositions: ["monumental-centered", "asymmetric-editorial"],
    usefulCombinations: ["typo-monumental-clean-sans", "sound-precision-click"],
    parameters: {
      wordHoldFrames: 24,
      negativeSpaceRatio: 0.72,
      textColor: "#FFFFFF",
    },
    knownFailureModes: [
      "Fails completely if text copy is wordy or vague. Words must be short, punchy statements ('This is', 'Not the outcome', 'Trade the event')",
    ],
    previewOrExample: {
      referenceFile: "c:/Users/USER/Documents/adcraft/your job/Screenshot (435).png",
      description: "Centered crisp off-white text on absolute dark void with 72% negative space and zero decorative elements.",
    },
    qualityScore: 9.9,
    tags: ["reference", "typography", "hook", "negative-space", "minimalist", "hedge"],
    provenIn: "Astra / Hedge Reference Climax Progression",
  },
];
