import { CreativeMemoryItem } from "../types";

export const TECHNICAL_PRECISION_ITEMS: CreativeMemoryItem[] = [
  {
    id: "comp-monolithic-hardware",
    name: "Monolithic Hardware Studio Presentation",
    type: "composition",
    whatItCommunicates: "Museum-grade industrial design, physical permanence, and uncompromising manufacturing craft.",
    creativeProblemSolved: "How to showcase a physical product or high-precision developer tool as an architectural artifact rather than a cheap consumer gadget.",
    emotionalEffect: ["precision", "awe", "prestige"],
    compatibleStyles: ["industrial-craft", "dark-saas", "minimalist"],
    compatibleCompositions: ["macro-extreme", "monolithic-vertical"],
    usefulCombinations: ["tech-pbr-titanium-pivot", "bg-matte-graphite-specular", "typo-monumental-clean-sans", "sound-precision-click", "trans-smooth-glide"],
    parameters: {
      negativeSpaceRatio: 0.54,
      cameraShot: "push-in",
      cameraIntensity: "subtle",
      lightingAngle: 45,
      specularSheenDelayFrames: 18,
    },
    knownFailureModes: [
      "Cluttered by too many secondary floating badges (keep badges <= 2)",
      "Ruined if bouncy spring curves are used instead of smooth deliberate glides",
      "Text clipping if headline exceeds 2 lines with monumental font size",
    ],
    previewOrExample: {
      referenceFile: "c:/Users/USER/Documents/adcraft/your job/Screenshot (388).png",
      description: "Heroic 3D hardware device framed against matte graphite with grazing rim lighting and architectural typography.",
    },
    qualityScore: 9.8,
    tags: ["hardware", "industrial", "monolith", "precision", "macro", "craft"],
    provenIn: "Teenage Engineering Industrial Monolith Benchmark",
  },
  {
    id: "tech-pbr-titanium-pivot",
    name: "PBR Titanium Chassis Y-Axis Pivot",
    type: "motion-technique",
    whatItCommunicates: "Tangible material honesty; light reacting to real metal bevels and tactile encoders.",
    creativeProblemSolved: "How to create high-end 3D hardware presence in Remotion without heavy external 3D engine lag.",
    emotionalEffect: ["precision", "delight", "awe"],
    compatibleStyles: ["industrial-craft", "dark-saas", "fintech-flow"],
    compatibleCompositions: ["monolithic-vertical", "macro-extreme"],
    usefulCombinations: ["comp-monolithic-hardware", "bg-matte-graphite-specular", "sound-precision-click"],
    parameters: {
      rotateYStart: -14,
      rotateYEnd: 8,
      perspective: 1400,
      specularSweepDurationFrames: 30,
      easing: "cubic-bezier(0.25, 1.0, 0.5, 1.0)",
    },
    knownFailureModes: [
      "Looks flat if specular rim gradient is omitted",
      "Overlaps with side-anchored text if rotation exceeds 22 degrees",
    ],
    previewOrExample: {
      referenceFile: "c:/Users/USER/Documents/adcraft/your job/Screenshot (388).png",
      codeSnippet: "transform: `perspective(1400px) rotateY(${rotY}deg) rotateX(4deg)`;",
    },
    qualityScore: 9.7,
    tags: ["3d", "titanium", "pivot", "hardware", "specular", "motion-technique"],
    provenIn: "Astra / Hedge Motion Benchmark (Act 2: iPhone 16 Pro 3D Showcase)",
  },
  {
    id: "tech-dof-floating-cards",
    name: "Multi-Plane Depth-of-Field Card Parallax",
    type: "motion-technique",
    whatItCommunicates: "Architectural spatial depth; primary interface elements floating in sharp focus over blurred technical layers.",
    creativeProblemSolved: "How to separate complex technical information into intelligible visual hierarchy using optical physics.",
    emotionalEffect: ["precision", "hyper-focus"],
    compatibleStyles: ["industrial-craft", "dark-saas", "cyber-terminal"],
    compatibleCompositions: ["asymmetric-grid", "macro-extreme"],
    usefulCombinations: ["comp-monolithic-hardware", "bg-matte-graphite-specular"],
    parameters: {
      heroZ: 48,
      supportingZ: -24,
      focalBlurPx: 6,
      differentialParallax: 0.14,
    },
    knownFailureModes: [
      "Over-blurring background makes important brand identifiers unreadable",
      "Text edge artifacts if filter blur is applied to text instead of card container",
    ],
    previewOrExample: {
      codeSnippet: "filter: `blur(${Math.abs(z - focalPlane) * 0.12}px)`;",
    },
    qualityScore: 9.6,
    tags: ["depth-of-field", "parallax", "spatial-depth", "blur", "optical"],
  },
  {
    id: "bg-matte-graphite-specular",
    name: "Matte Studio Graphite with Ambient Rim Luminescence",
    type: "background",
    whatItCommunicates: "Restrained studio sophistication; premium acoustics laboratory.",
    creativeProblemSolved: "How to provide maximum contrast for hardware metals and crisp technical typography without distraction.",
    emotionalEffect: ["precision", "prestige"],
    compatibleStyles: ["industrial-craft", "dark-saas", "minimalist"],
    compatibleCompositions: ["macro-extreme", "monolithic-vertical"],
    usefulCombinations: ["comp-monolithic-hardware", "typo-monumental-clean-sans", "tech-pbr-titanium-pivot"],
    parameters: {
      primaryColor: "#121316",
      gradientTo: "#1A1B20",
      rimGlowColor: "#FF440022",
      rimPosition: "top-right",
      subtleDustEmbers: true,
    },
    knownFailureModes: [
      "If rim glow is too saturated, it looks like a gaming rig rather than precision audio equipment",
    ],
    previewOrExample: {
      description: "Fine-grained matte studio graphite plate with delicate directional backlight rim.",
    },
    qualityScore: 9.5,
    tags: ["background", "graphite", "studio", "matte", "rim-light"],
  },
  {
    id: "typo-monumental-clean-sans",
    name: "Monumental Clean Sans with Razor Kerning",
    type: "typography-treatment",
    whatItCommunicates: "Absolute authority and clarity; zero marketing jargon.",
    creativeProblemSolved: "How to present bold product statements with supreme confidence without shouting or resorting to gimmicky animations.",
    emotionalEffect: ["precision", "prestige", "awe"],
    compatibleStyles: ["industrial-craft", "dark-saas", "minimalist"],
    compatibleCompositions: ["monolithic-vertical", "macro-extreme"],
    usefulCombinations: ["comp-monolithic-hardware", "bg-matte-graphite-specular", "sound-precision-click"],
    parameters: {
      fontSize: 66,
      fontWeight: 800,
      letterSpacing: "-0.035em",
      animation: "cinematic-scale",
      holdFrames: 45,
    },
    knownFailureModes: [
      "Collides with top edge of 3D window if posY > 24% in composite layouts",
      "Do not use colorful gradient text fills; stick to crisp pure off-white (#EDEDED)",
    ],
    previewOrExample: {
      codeSnippet: "<KineticText text='Form follows emotion. Precision meets play.' fontSize={66} fontWeight={800} />",
    },
    qualityScore: 9.8,
    tags: ["typography", "monumental", "sans", "clean", "authority"],
    provenIn: "Teenage Engineering Benchmark Scene 1",
  },
  {
    id: "trans-smooth-glide",
    name: "Cinematic Push-In Glide Transition",
    type: "transition",
    whatItCommunicates: "Seamless continuity; drawing the viewer deeper into the physical details of the device.",
    creativeProblemSolved: "How to shift scenes without breaking visual immersion or feeling like a typical slide/wipe slideshow.",
    emotionalEffect: ["precision", "awe"],
    compatibleStyles: ["industrial-craft", "dark-saas", "editorial-light"],
    compatibleCompositions: ["all"],
    usefulCombinations: ["comp-monolithic-hardware", "tech-pbr-titanium-pivot"],
    parameters: {
      durationFrames: 18,
      scaleFrom: 1.0,
      scaleTo: 1.08,
      crossfadeEase: "easeInOutCubic",
    },
    knownFailureModes: [
      "Must not have black dips; frames must overlap smoothly via TransitionSeries",
    ],
    previewOrExample: {
      description: "Smooth 18-frame push-in cross-glide with zero visual friction.",
    },
    qualityScore: 9.6,
    tags: ["transition", "glide", "push-in", "cinematic"],
  },
  {
    id: "sound-precision-click",
    name: "Tactile Mechanical Switch & Encoder Clicks",
    type: "sound-cue",
    whatItCommunicates: "Physical tactile gratification; the satisfaction of clicking a precision-milled aluminum knob.",
    creativeProblemSolved: "How to make software/hardware interactions feel physical and satisfying to the ear.",
    emotionalEffect: ["precision", "delight"],
    compatibleStyles: ["industrial-craft", "dark-saas", "cyber-terminal"],
    compatibleCompositions: ["monolithic-vertical", "asymmetric-grid"],
    usefulCombinations: ["comp-monolithic-hardware", "tech-pbr-titanium-pivot"],
    parameters: {
      frequencyHz: 3200,
      decayMs: 24,
      spatialPan: 0.1,
    },
    knownFailureModes: [
      "Sounds like an annoying glitch if triggered more than 4 times per second",
    ],
    previewOrExample: {
      description: "Crisp, dampened mechanical keyboard / dial click synced to element reveals.",
    },
    qualityScore: 9.7,
    tags: ["audio", "tactile", "switch", "mechanical", "click"],
  },
];
