import { CreativeMemoryItem } from "../types";

export const TENSION_OVERLOAD_ITEMS: CreativeMemoryItem[] = [
  {
    id: "comp-perspective-conveyor-friction",
    name: "3D Perspective Friction Conveyor",
    type: "composition",
    whatItCommunicates: "An endless, overwhelming flood of pending tasks, alerts, or manual steps drowning the user.",
    creativeProblemSolved: "How to visually represent chaos, backlog fatigue, and fragmentation without looking like a generic bullet list or cheap stock illustration.",
    emotionalEffect: ["tension", "visual-overload", "anxiety", "urgency"],
    compatibleStyles: ["dark-saas", "cyber-terminal", "fintech-flow"],
    compatibleCompositions: ["perspective-card-grid", "diagonal-shear"],
    usefulCombinations: ["tech-conveyor-belt-3d", "bg-tension-shear-grid", "typo-stagger-stress", "sound-tension-hum", "trans-whip-snap"],
    parameters: {
      perspectiveDegrees: 48,
      tiltY: -18,
      continuousScrollSpeed: 4.8,
      staggerDelayFrames: 6,
      ambientGlowColor: "#EF4444",
      vignetteIntensity: 0.55,
    },
    knownFailureModes: [
      "Overlaps centered headline if headline posY > 30%",
      "Card contrast disappears if cards don't have distinct 1px border (#ffffff15)",
      "Motion sickness if scroll speed exceeds 6.5 px/frame",
    ],
    previewOrExample: {
      referenceFile: "c:/Users/USER/Documents/adcraft/your job/Screenshot (365).png",
      codeSnippet: "<PerspectiveCardGrid cards={frictionItems} continuousScrollSpeed={4.8} tiltY={-18} />",
      description: "Infinite cascading cards flowing downwards in 3D perspective with ominous warning illumination.",
    },
    qualityScore: 9.6,
    tags: ["tension", "backlog", "friction", "conveyor", "overload", "3d"],
    provenIn: "Astra / Hedge Motion Benchmark (Act 1: Endless manual prediction tasks)",
  },
  {
    id: "comp-notification-cascade-barrage",
    name: "Staggered Incident Notification Barrage",
    type: "composition",
    whatItCommunicates: "Constant interruptions, critical alerts, and fragmented communications shattering developer focus.",
    creativeProblemSolved: "How to show enterprise urgency and cognitive interruption across multiple apps (Slack, Jira, PagerDuty, Teams) in a compact, aesthetic way.",
    emotionalEffect: ["tension", "visual-overload", "urgency"],
    compatibleStyles: ["dark-saas", "cyber-terminal", "broadcast-bold"],
    compatibleCompositions: ["asymmetric-grid", "cascade-stack"],
    usefulCombinations: ["tech-snappy-card-drop", "bg-tension-shear-grid", "sound-rapid-blips", "trans-glitch-wipe"],
    parameters: {
      staggerFrames: 7,
      cardAngle: -5,
      scaleDrop: 0.98,
      severityBadgeColor: "#EF4444",
    },
    knownFailureModes: [
      "Obscures headline if placed higher than Y:45%",
      "Text truncation inside notification pills if message > 55 characters",
      "Feels too enterprise-stiff if applied to consumer or luxury lifestyle brands",
    ],
    previewOrExample: {
      codeSnippet: "<NotificationCascade items={alertItems} staggerFrames={7} angle={-5} />",
      description: "4 staggered floating notification cards snapping in with spring overshoot and red urgency badges.",
    },
    qualityScore: 9.4,
    tags: ["alerts", "notifications", "incident", "interruption", "urgency"],
    provenIn: "Wordsmith Widescreen 16:9 Benchmark",
  },
  {
    id: "tech-conveyor-belt-3d",
    name: "3D Continuous Y-Axis Conveyor Glide",
    type: "motion-technique",
    whatItCommunicates: "Relentless continuous momentum; an inescapable conveyor belt of work.",
    creativeProblemSolved: "How to maintain smooth continuous motion in Remotion without jerky loops or sudden snap stops.",
    emotionalEffect: ["tension", "visual-overload", "urgency"],
    compatibleStyles: ["dark-saas", "cyber-terminal", "fintech-flow"],
    compatibleCompositions: ["perspective-card-grid", "monolithic-vertical"],
    usefulCombinations: ["comp-perspective-conveyor-friction", "bg-tension-shear-grid", "sound-tension-hum"],
    parameters: {
      continuousScrollSpeed: 4.5,
      cameraGlide: { startY: 12, endY: -18 },
      easing: "cubic-bezier(0.16, 1.0, 0.3, 1.0)",
    },
    knownFailureModes: [
      "Stutter occurs if frame rate drops below 30fps",
      "Disorienting if combined with rapid horizontal camera panning",
    ],
    previewOrExample: {
      referenceFile: "c:/Users/USER/Documents/adcraft/your job/Screenshot (365).png",
      codeSnippet: "const yOffset = (frame * continuousScrollSpeed) % totalGridHeight;",
    },
    qualityScore: 9.7,
    tags: ["conveyor", "scroll", "glide", "continuous", "motion-physics"],
    provenIn: "Astra / Hedge Motion Benchmark",
  },
  {
    id: "bg-tension-shear-grid",
    name: "Sheared Obsidian Void with Warning Embers",
    type: "background",
    whatItCommunicates: "Critical tension, high stakes, late-night production outages.",
    creativeProblemSolved: "How to create a dark atmospheric void that feels active and dangerous rather than flat black.",
    emotionalEffect: ["tension", "urgency"],
    compatibleStyles: ["dark-saas", "cyber-terminal"],
    compatibleCompositions: ["perspective-card-grid", "asymmetric-grid"],
    usefulCombinations: ["comp-perspective-conveyor-friction", "typo-stagger-stress", "sound-tension-hum"],
    parameters: {
      primaryColor: "#0A0D14",
      glowColor: "#EF444433",
      shearAngle: 12,
      grainIntensity: 0.12,
    },
    knownFailureModes: [
      "Red glow can look cheap if opacity exceeds 0.25",
      "Clashes with serene brand palettes (e.g. mint, amber, light gray)",
    ],
    previewOrExample: {
      description: "Deep obsidian canvas with subtle angled micro-grid and low-frequency red-orange breathing glow.",
    },
    qualityScore: 9.3,
    tags: ["background", "dark", "grid", "warning", "tension"],
  },
  {
    id: "typo-stagger-stress",
    name: "Staggered High-Stress Kinetic Punch",
    type: "typography-treatment",
    whatItCommunicates: "A sharp, provocative question that forces the viewer to acknowledge their acute problem.",
    creativeProblemSolved: "How to stop the viewer's scroll instantly with stark linguistic impact without looking like clickbait.",
    emotionalEffect: ["tension", "urgency", "hyper-focus"],
    compatibleStyles: ["dark-saas", "cyber-terminal", "broadcast-bold"],
    compatibleCompositions: ["asymmetric-grid", "diagonal-shear"],
    usefulCombinations: ["comp-perspective-conveyor-friction", "bg-tension-shear-grid", "sound-heavy-thud"],
    parameters: {
      fontSize: 64,
      fontWeight: 800,
      staggerDelayFrames: 3,
      glowPunchColor: "#EF4444",
      letterSpacing: "-0.03em",
    },
    knownFailureModes: [
      "Text wrapping breaks if word contains more than 14 characters without hyphenation",
      "Overlaps with 3D elements if posY is between 40% and 65%",
    ],
    previewOrExample: {
      codeSnippet: "<KineticText animation='glow-punch' highlightWords={['losing', '15+', 'broken']} />",
    },
    qualityScore: 9.5,
    tags: ["typography", "kinetic", "stagger", "punch", "headline"],
  },
  {
    id: "trans-whip-snap",
    name: "Directional Whip-Pan Snap",
    type: "transition",
    whatItCommunicates: "Sudden escalation; an urgent shift in perspective.",
    creativeProblemSolved: "How to transition between problem scenes without letting the tension dissipate in a slow fade.",
    emotionalEffect: ["tension", "urgency"],
    compatibleStyles: ["dark-saas", "cyber-terminal"],
    compatibleCompositions: ["all"],
    usefulCombinations: ["comp-perspective-conveyor-friction", "typo-stagger-stress"],
    parameters: {
      durationFrames: 12,
      blurAmount: 16,
      direction: "from-right",
    },
    knownFailureModes: [
      "Can feel jarring if the incoming scene has a radically different luminance level",
    ],
    previewOrExample: {
      description: "12-frame high-velocity horizontal blur transition snapping into the next climax.",
    },
    qualityScore: 9.2,
    tags: ["transition", "whip-pan", "snap", "high-velocity"],
  },
  {
    id: "sound-tension-hum",
    name: "Sub-Bass Tension Drone with Micro-Clicks",
    type: "sound-cue",
    whatItCommunicates: "Underlying system stress; impending threshold breach.",
    creativeProblemSolved: "How to support visual chaos with sound without creating an unlistenable cacophony.",
    emotionalEffect: ["tension", "anxiety", "hyper-focus"],
    compatibleStyles: ["dark-saas", "cyber-terminal"],
    compatibleCompositions: ["perspective-card-grid", "asymmetric-grid"],
    usefulCombinations: ["comp-perspective-conveyor-friction", "bg-tension-shear-grid"],
    parameters: {
      pitchHz: 55,
      rumbleVolume: 0.7,
      microClickIntervalFrames: 6,
    },
    knownFailureModes: [
      "Drowns out voiceover if master gain > -12dB",
    ],
    previewOrExample: {
      description: "55Hz sine sub-rumble with synced subtle tactile click ticks on each card pass.",
    },
    qualityScore: 9.4,
    tags: ["audio", "tension", "sub-bass", "drone"],
  },
];
