import { AssetMetadata } from "../types";

export const ATMOSPHERE_ASSETS: AssetMetadata[] = [
  {
    id: "atmo-editorial-studio",
    category: "atmosphere",
    name: "Editorial Paper & Roving Studio Spotlight",
    description: "Analog paper noise, warm roving studio key light, and delicate floating dust particles.",
    tags: ["light", "editorial", "paper", "studio", "analog"],
    brandFit: ["editorial-light", "authoritative", "minimalist"],
    properties: {
      grain: 0.14,
      vignette: 0.32,
      haze: 0.1,
      particleCount: 35,
      hasRovingLight: true,
      hasPaperGrain: true,
      hasVolumetricBloom: false,
    },
    usageNotes: "Standard for light-mode brands, serif typography, and premium editorial advertisements.",
  },
  {
    id: "atmo-dark-cinematic",
    category: "atmosphere",
    name: "Dark Cinematic & Volumetric Light Leaks",
    description: "Deep cinematic vignette, dual-color volumetric light leaks, and luminous floating bokeh particles.",
    tags: ["dark", "cinematic", "volumetric", "bokeh", "dramatic"],
    brandFit: ["authoritative", "technical", "enterprise"],
    properties: {
      grain: 0.1,
      vignette: 0.45,
      haze: 0.18,
      particleCount: 35,
      hasRovingLight: false,
      hasVolumetricBloom: true,
    },
    usageNotes: "Standard for broadcast-grade dark SaaS ads. Creates unmistakable cinema quality on 4K/6K displays.",
  },
  {
    id: "atmo-clean-tech",
    category: "atmosphere",
    name: "Clean Tech & Precision Micro-Particles",
    description: "Minimalist, restrained atmosphere with razor-sharp contrast, low grain, and subtle digital depth.",
    tags: ["clean", "tech", "restrained", "developer-tools", "minimal"],
    brandFit: ["technical", "minimalist", "developer-focused"],
    properties: {
      grain: 0.04,
      vignette: 0.18,
      haze: 0.05,
      particleCount: 20,
      hasRovingLight: false,
      hasVolumetricBloom: false,
    },
    usageNotes: "Used when the product UI must remain 100% sharp and unmuted by heavy film textures.",
  },
  {
    id: "atmo-film-grain-35mm",
    category: "atmosphere",
    name: "Authentic 35mm Film Grain Stock",
    description: "Multi-octave temporal film noise emulation replicating Kodak Vision3 500T aesthetic.",
    tags: ["film", "grain", "35mm", "analog", "texture", "cinematic"],
    brandFit: ["luxury", "creative", "editorial-light", "authoritative"],
    properties: {
      grain: 0.22,
      vignette: 0.38,
      haze: 0.12,
      particleCount: 40,
      hasRovingLight: true,
      hasPaperGrain: true,
      hasVolumetricBloom: true,
    },
    usageNotes: "Gives ads the warm, organic tactile sensation of high-end Super 35 film cameras.",
  },
  {
    id: "atmo-dust-scratches",
    category: "atmosphere",
    name: "Atmospheric Dust Motes & Volumetric Rays",
    description: "Floating physical dust motes illuminated by anamorphic lens rays and optical haze.",
    tags: ["dust", "particles", "anamorphic", "atmospheric", "cinematic"],
    brandFit: ["authoritative", "cinematic", "enterprise"],
    properties: {
      grain: 0.12,
      vignette: 0.42,
      haze: 0.22,
      particleCount: 55,
      hasRovingLight: false,
      hasVolumetricBloom: true,
    },
    usageNotes: "Simulates an authentic physical optical lens capturing light inside a sunlit studio space.",
  },
];
