import { AssetMetadata } from "../types";

export const BACKGROUND_ASSETS: AssetMetadata[] = [
  // 1. Procedural & Static Clean Backgrounds
  {
    id: "bg-editorial-sand-grain",
    category: "background",
    name: "Editorial Sand & Paper Grain",
    description: "Warm ivory and sand paper texture with subtle procedural grain and roving studio spotlight.",
    tags: ["light", "editorial", "warm", "paper", "luxury", "legal", "fintech"],
    brandFit: ["editorial-light", "authoritative", "minimalist"],
    mediaType: "code",
    properties: {
      color: "#F8F7F3",
      gradientTo: "#F1EFE9",
      angle: 135,
      type: "gradient",
      glowOrb: false,
      hasPaperGrain: true,
      hasStudioLight: true,
      dotGridOpacity: 0.05,
    },
    usageNotes: "Best paired with serif typography (Newsreader, Playfair), dark navy text, and soft elevated cards.",
  },
  {
    id: "bg-cinematic-midnight-mesh",
    category: "background",
    name: "Cinematic Midnight Mesh",
    description: "Deep obsidian-to-navy radial ambient bloom with soft multi-point volumetric light leaks.",
    tags: ["dark", "cinematic", "enterprise", "saas", "authoritative"],
    brandFit: ["authoritative", "technical", "enterprise"],
    mediaType: "code",
    properties: {
      color: "#0B0F19",
      gradientTo: "#0F172A",
      angle: 140,
      type: "gradient",
      glowOrb: true,
      hasPaperGrain: false,
      hasStudioLight: false,
      dotGridOpacity: 0.08,
    },
    usageNotes: "Standard for broadcast-grade SaaS ads. Pairs naturally with frosted glass and titanium device mockups.",
  },
  {
    id: "bg-cyber-obsidian-glow",
    category: "background",
    name: "Cyber Obsidian & Electric Accent",
    description: "Ultra-deep obsidian background with high-contrast electric accent rim lighting and deep vignette.",
    tags: ["dark", "high-velocity", "ai-dev", "crypto", "electric"],
    brandFit: ["high-velocity", "technical", "cyberpunk"],
    mediaType: "code",
    properties: {
      color: "#050508",
      gradientTo: "#0B0B14",
      angle: 160,
      type: "gradient",
      glowOrb: true,
      hasPaperGrain: false,
      hasStudioLight: false,
      dotGridOpacity: 0.12,
    },
    usageNotes: "High-contrast backdrop for rapid code terminals, neon counters, and AI agent execution cards.",
  },
  {
    id: "bg-studio-clean-slate",
    category: "background",
    name: "Studio Clean Slate",
    description: "Subtle neutral slate gradient with a crisp engineering micro-dot matrix pattern.",
    tags: ["neutral", "slate", "developer-tools", "minimalist"],
    brandFit: ["technical", "minimalist", "developer-focused"],
    mediaType: "code",
    properties: {
      color: "#0E1424",
      gradientTo: "#1E293B",
      angle: 125,
      type: "gradient",
      glowOrb: true,
      hasPaperGrain: false,
      hasStudioLight: false,
      dotGridOpacity: 0.09,
    },
    usageNotes: "Linear and Raycast aesthetic. Exceptional for kanban boards, code diffs, and precise tables.",
  },

  // 2. High-Depth Video Loops (Royalty-Free / Remotion Loop)
  {
    id: "bg-video-dark-aurora",
    category: "background",
    name: "Dark Aurora Fluid Motion Plate",
    description: "Volumetric midnight fluid waves with drifting neon highlights and subtle atmospheric haze.",
    tags: ["video", "loop", "cinematic", "aurora", "atmospheric", "premium"],
    brandFit: ["authoritative", "technical", "modern", "enterprise"],
    mediaType: "video",
    src: "assets/backgrounds/dark-aurora.mp4",
    blendMode: "screen",
    playbackRate: 1.0,
    properties: {
      fallbackColor: "#0B0F19",
      glowOrb: false,
      hasPaperGrain: false,
      hasStudioLight: false,
      dotGridOpacity: 0.04,
    },
    usageNotes: "Elevates standard SaaS UI cards into filmic broadcast presentations.",
  },
  {
    id: "bg-video-cyber-grid",
    category: "background",
    name: "Cyber Perspective Grid Flight",
    description: "Endless 3D vector cyberspace grid moving at high velocity with electric horizon bloom.",
    tags: ["video", "loop", "cyber", "grid", "high-velocity", "developer-tools"],
    brandFit: ["high-velocity", "technical", "crypto"],
    mediaType: "video",
    src: "assets/backgrounds/cyber-grid.mp4",
    blendMode: "screen",
    playbackRate: 1.2,
    properties: {
      fallbackColor: "#050508",
      glowOrb: true,
      hasPaperGrain: false,
      hasStudioLight: false,
      dotGridOpacity: 0.0,
    },
    usageNotes: "Ideal for hook scenes and speedrun product demos demonstrating sub-millisecond latency.",
  },
  {
    id: "bg-video-minimal-ambient",
    category: "background",
    name: "Minimal Editorial Ambient Smoke",
    description: "Subtle roving ivory smoke drift designed for luxury and editorial light brand identities.",
    tags: ["video", "loop", "light", "editorial", "smoke", "luxury"],
    brandFit: ["editorial-light", "minimalist", "luxury"],
    mediaType: "video",
    src: "assets/backgrounds/minimal-ambient.mp4",
    blendMode: "multiply",
    playbackRate: 0.8,
    properties: {
      fallbackColor: "#F8F7F3",
      glowOrb: false,
      hasPaperGrain: true,
      hasStudioLight: true,
      dotGridOpacity: 0.04,
    },
    usageNotes: "Perfect for contract redline diffs and enterprise legal/fintech brand spots.",
  },
  {
    id: "bg-video-cosmic-particles",
    category: "background",
    name: "Deep Space Particle Field Loop",
    description: "Slow-drifting 3D micro-particles and subtle interstellar gas clouds with infinite depth.",
    tags: ["video", "loop", "particles", "cosmic", "deep-depth", "ai"],
    brandFit: ["technical", "authoritative", "enterprise"],
    mediaType: "video",
    src: "assets/backgrounds/cosmic-particles.mp4",
    blendMode: "screen",
    playbackRate: 0.9,
    properties: {
      fallbackColor: "#090D16",
      glowOrb: true,
      hasPaperGrain: false,
      hasStudioLight: false,
      dotGridOpacity: 0.05,
    },
    usageNotes: "Universal tech background providing spatial depth behind floating mockups.",
  },

  // 3. Real-Time Mathematical Shader Gradients (Offline, 60fps, Zero Compression)
  {
    id: "bg-shader-fluid-aurora",
    category: "background",
    name: "Fluid Aurora Shader",
    description: "Deterministic Canvas mathematical fluid simulation with organic sinusoidal wave propagation.",
    tags: ["shader", "fluid", "canvas", "deterministic", "aurora", "modern"],
    brandFit: ["modern", "technical", "authoritative", "high-velocity"],
    mediaType: "shader",
    properties: {
      shaderPreset: "aurora",
      speed: 1.0,
      opacity: 0.9,
      fallbackColor: "#0B0F19",
      glowOrb: false,
      dotGridOpacity: 0.06,
    },
    usageNotes: "Guaranteed offline rendering at broadcast 4K resolution with fluid wave dynamics.",
  },
  {
    id: "bg-shader-domain-warp",
    category: "background",
    name: "Domain Warp Flow Shader",
    description: "Stripe and Linear style mathematical domain-warping color vortex field.",
    tags: ["shader", "domain-warp", "stripe-aesthetic", "fintech", "developer-tools"],
    brandFit: ["technical", "fintech", "developer-focused"],
    mediaType: "shader",
    properties: {
      shaderPreset: "warp",
      speed: 0.8,
      opacity: 0.85,
      fallbackColor: "#080B12",
      glowOrb: true,
      dotGridOpacity: 0.05,
    },
    usageNotes: "The gold standard aesthetic for modern developer infrastructure and payment fintech.",
  },
  {
    id: "bg-shader-mesh-blobs",
    category: "background",
    name: "Organic Mesh Blobs Shader",
    description: "Floating Gaussian color nodes with dynamic trigonometric dispersion and chromatic blur.",
    tags: ["shader", "mesh-gradient", "blobs", "soft", "saas"],
    brandFit: ["authoritative", "minimalist", "modern"],
    mediaType: "shader",
    properties: {
      shaderPreset: "mesh-blobs",
      speed: 1.1,
      opacity: 0.95,
      fallbackColor: "#0E1424",
      glowOrb: false,
      dotGridOpacity: 0.07,
    },
    usageNotes: "Warm, inviting background for collaboration, AI copilot, and productivity SaaS ads.",
  },
  {
    id: "bg-shader-hexagonal-grid",
    category: "background",
    name: "Hexagonal Tech Grid",
    description: "Subtle moving hexagonal grid pattern perfect for mobile fintech.",
    tags: ["shader", "grid", "hexagonal", "tech", "modern"],
    brandFit: ["modern", "technical", "fintech"],
    mediaType: "shader",
    properties: {
      shaderPreset: "hexagonal",
      speed: 1.0,
      opacity: 0.3,
      fallbackColor: "#111111",
      glowOrb: false,
      dotGridOpacity: 0.0,
    },
    usageNotes: "Standard premium tech pattern, pairs perfectly with floating phone mockups.",
  },
];
