import { AssetMetadata } from "../types";

export const BUTTON_ASSETS: AssetMetadata[] = [
  {
    id: "btn-glow-primary",
    category: "button",
    name: "Luminous Glow Primary CTA",
    description: "High-converting action button with radial brand glow bloom and animated breathing ripple ring.",
    tags: ["cta", "glow", "high-converting", "bold", "pulsing"],
    brandFit: ["authoritative", "technical", "high-velocity", "fintech"],
    properties: {
      borderRadius: "9999px",
      padding: "20px 48px",
      fontSize: "22px",
      fontWeight: 700,
      hasPulse: true,
      hasRipple: true,
      shadowBloomIntensity: 35,
      borderSheen: "1px solid rgba(255, 255, 255, 0.2)",
    },
    usageNotes: "Default for final CTA scene in high-energy SaaS ads. Choreographed with cursor click.",
  },
  {
    id: "btn-minimal-editorial",
    category: "button",
    name: "Minimal Editorial Monolith",
    description: "Understated, high-contrast monochrome button designed to complement serif typography and editorial layouts.",
    tags: ["editorial", "minimal", "monochrome", "crisp", "luxury"],
    brandFit: ["editorial-light", "minimalist", "authoritative"],
    properties: {
      borderRadius: "9999px",
      padding: "18px 44px",
      fontSize: "20px",
      fontWeight: 700,
      hasPulse: false,
      hasRipple: true,
      shadowBloomIntensity: 12,
      borderSheen: "1px solid rgba(0, 0, 0, 0.12)",
    },
    usageNotes: "Required for editorial light mode and luxury SaaS brands where neon glows look amateurish.",
  },
  {
    id: "btn-ghost-glass",
    category: "button",
    name: "Translucent Ghost Glass",
    description: "Frosted translucent glass button with subtle backdrop blur and refined edge specular highlight.",
    tags: ["glass", "ghost", "secondary", "translucent"],
    brandFit: ["technical", "modern", "minimalist"],
    properties: {
      borderRadius: "9999px",
      padding: "16px 38px",
      fontSize: "19px",
      fontWeight: 600,
      hasPulse: false,
      hasRipple: false,
      shadowBloomIntensity: 0,
      borderSheen: "1px solid rgba(255, 255, 255, 0.25)",
      backdropFilter: "blur(24px)",
    },
    usageNotes: "Ideal for secondary action triggers or minimalist navigation pills.",
  },
  {
    id: "btn-holographic-shimmer",
    category: "button",
    name: "Holographic Dynamic Shimmer",
    description: "Angled metallic rainbow gradient border with dynamic light beam shimmer animation.",
    tags: ["holographic", "shimmer", "future", "ai", "crypto"],
    brandFit: ["high-velocity", "cyberpunk", "creative"],
    properties: {
      borderRadius: "9999px",
      padding: "20px 48px",
      fontSize: "22px",
      fontWeight: 700,
      hasPulse: true,
      hasRipple: true,
      shadowBloomIntensity: 45,
      borderSheen: "2px solid rgba(168, 85, 247, 0.5)",
      shimmer: true,
    },
    usageNotes: "Produces maximum eye attraction on next-generation AI productivity platforms.",
  },
  {
    id: "btn-enterprise-pill",
    category: "button",
    name: "Enterprise Command Pill",
    description: "High-density developer command pill with subtle hotkey badge indicator.",
    tags: ["developer", "command-palette", "dense", "enterprise"],
    brandFit: ["technical", "developer-focused", "authoritative"],
    properties: {
      borderRadius: "12px",
      padding: "16px 36px",
      fontSize: "18px",
      fontWeight: 600,
      hasPulse: false,
      hasRipple: false,
      shadowBloomIntensity: 10,
      borderSheen: "1px solid rgba(255, 255, 255, 0.2)",
      hasHotkey: true,
    },
    usageNotes: "For developer tools highlighting keyboard-first shortcuts (e.g. ⌘K).",
  },
];
