import { AssetMetadata } from "../types";

export const DEVICE_ASSETS: AssetMetadata[] = [
  {
    id: "device-macos-safari-studio",
    category: "device",
    name: "macOS Safari Studio Window",
    description: "3D perspective desktop browser window with authentic macOS traffic lights, discreet URL pill, and frosted toolbar.",
    tags: ["desktop", "browser", "macos", "window", "3d-tilt", "sequoia"],
    brandFit: ["authoritative", "editorial-light", "technical", "enterprise"],
    mediaType: "code",
    properties: {
      type: "browser",
      deviceType: "studio-browser",
      perspective: "1400px",
      borderRadius: "18px",
      headerHeight: "48px",
      hasTrafficLights: true,
      hasUrlBar: true,
      tiltAngles: { rotateX: 6, rotateY: -6 },
      shadowDark: "0 40px 90px rgba(0, 0, 0, 0.7), 0 12px 30px rgba(0, 0, 0, 0.3)",
      shadowLight: "0 35px 70px rgba(0, 0, 0, 0.1), 0 8px 20px rgba(0, 0, 0, 0.04)",
    },
    usageNotes: "Universal desktop frame for kanban boards, code diffs, legal redlining, and complex SaaS dashboards.",
  },
  {
    id: "device-macbook-pro-16",
    category: "device",
    name: "MacBook Pro 16\" Space Black",
    description: "Photorealistic Apple MacBook Pro 16-inch hardware frame with Liquid Retina XDR 16:10 ratio, camera notch, and aluminum chassis.",
    tags: ["laptop", "macbook", "hardware", "apple", "notch", "16-inch", "luxury"],
    brandFit: ["authoritative", "technical", "enterprise", "developer-focused"],
    mediaType: "code",
    properties: {
      type: "laptop",
      deviceType: "macbook-pro-16",
      perspective: "1400px",
      borderRadius: "22px",
      hasNotch: true,
      hasHinge: true,
      aspectRatio: "16 / 10",
      tiltAngles: { rotateX: 8, rotateY: -6 },
      shadowDark: "0 45px 95px rgba(0, 0, 0, 0.75), 0 15px 35px rgba(0, 0, 0, 0.5)",
      shadowLight: "0 35px 80px rgba(0, 0, 0, 0.14), 0 10px 25px rgba(0, 0, 0, 0.05)",
    },
    usageNotes: "The ultimate flagship frame for full-screen web apps, IDEs, and high-impact enterprise hero demonstrations.",
  },
  {
    id: "device-iphone16-pro-titanium",
    category: "device",
    name: "iPhone 16 Pro Natural Titanium",
    description: "Pure CSS/React 3D mobile chassis with brushed titanium rim, active Dynamic Island pill, and razor-thin bezels.",
    tags: ["mobile", "ios", "iphone", "iphone16", "titanium", "dynamic-island", "fintech"],
    brandFit: ["modern", "fintech", "high-velocity", "consumer"],
    mediaType: "code",
    properties: {
      type: "phone",
      deviceType: "iphone16-pro",
      perspective: "1400px",
      bezelRadius: "56px",
      rimFinish: "titanium",
      hasDynamicIsland: true,
      hasGlassReflection: true,
      pedestalShadow: true,
      tiltAngles: { rotateX: 10, rotateY: -8 },
      shadowDark: "0 40px 85px rgba(0, 0, 0, 0.8)",
      shadowLight: "0 30px 70px rgba(0, 0, 0, 0.16)",
    },
    usageNotes: "Essential for fintech wallet flows, mobile onboarding speedruns, and iOS app showcase ads.",
  },
  {
    id: "device-ipad-pro-m4",
    category: "device",
    name: "iPad Pro M4 Ultra-Thin Frame",
    description: "Minimalist aluminum tablet enclosure with edge-to-edge 4:3 display ratio and clean uniform borders.",
    tags: ["tablet", "ipad", "hardware", "touch", "creative"],
    brandFit: ["modern", "creative", "minimalist", "enterprise"],
    mediaType: "code",
    properties: {
      type: "tablet",
      deviceType: "ipad-pro",
      perspective: "1400px",
      borderRadius: "36px",
      aspectRatio: "4 / 3",
      tiltAngles: { rotateX: 7, rotateY: -5 },
      shadowDark: "0 35px 80px rgba(0, 0, 0, 0.6)",
      shadowLight: "0 25px 60px rgba(0, 0, 0, 0.12)",
    },
    usageNotes: "Great for design tooling, document markup, and responsive tablet layout demonstrations.",
  },
];
